services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Ayacoo\AyacooSoundcloud\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Helper/*'

  Ayacoo\AyacooSoundcloud\Command\UpdateMetadataCommand:
    tags:
      - name: 'console.command'
        command: 'soundcloud:updateMetadata'
        description: 'Updates the Soundcloud metadata'
        schedulable: true
